//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.18 at 11:28:07 AM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:rm.bulk.hcl.neo.com:schema.objecttype.20141806", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hcl.neo.cms.microservices.excel.schema_objecttype;
