---
server:
  port: 50311

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    
# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 
    
# Map the error path to error template (for Thymeleaf)
error:
  path: /error
  
logging:
  file: eurekaserver.log