---

spring:
 activemq: 
    broker-url: tcp://10.99.18.152:61616

# HTTP Server
server:
  port: 0   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.99.18.152:50311/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress : true
    nonSecurePort: ${server.port:50315}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

bulk: 
  defaultImportLocation: /Testing
  
jms: 
  queue: 
    processService: processQueue